### PR TITLE
Was Merged PR from NestONDC - RishiMondal

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @sanjay-kv 

This was my Merged PR from NestONDC - Rishi Mondal 
1) Improved the Complete UI of the FAQ Page
PR Link : https://github.com/MAVRICK-1/e-commerce_website/pull/396

image

2) The below PR was unmerged, I'm unable to find the PR link but this is the PR -
Created A Dedicated Feedback Page for the website
https://github.com/aslams2020/e-commerce_website/commit/a8b9dd24bd0151b9ee51aacde8914a1577c6ef19

image

### CODE REVIEW

**Comment by aslams2020** [comment]
@sanjay-kv Please review these PRs from NestONDC

**Comment by aslams2020** [comment]
@sanjay-kv Please review it

**Comment by aslams2020** [comment]
@sanjay-kv
 For **First PR,** it was **merged with "Level2"** 
And the **Second PR** based on the changes **"Level3 or Level2"** may have given by rishimondal

So **total points needed to be added** are - **70points**

**Comment by aslams2020** [comment]
@sanjay-kv 
There are more **25points** needed to be added.

**Comment by sanjay-kv** [comment]
raise new pr

**Comment by aslams2020** [comment]
@sanjay-kv Done.. Please check

**Pull request merged**
